package Pokemon


fun main() {
    formarTime("player")
}

fun getPlayers(): List<String> {
    val regex = Regex("^[A-Za-z]+\$")
    var player1 = ""
    var player2 = ""
    do {
        println("Digite o nome do primeiro player:")
        player1 = readlnOrNull() ?: "-1"
    } while (!(player1.matches(regex)))
    do {
        println("Digite o nome do primeiro player:")
        player2 = readlnOrNull() ?: "-1"
    } while (!(player2.matches(regex)))

    return listOf(player1, player2)
}

fun formarTime(player:String): Map<Int, Map<String, List<String>?>> {
    val pokemons = Pokemons()
    val pokemonsDisponiveis = mapOf(
        1 to pokemons.bulbasaur,
        2 to pokemons.ivysaur,
        3 to pokemons.venusaur,
        4 to pokemons.charmander,
        5 to pokemons.charmeleon,
        6 to pokemons.charizard,
        7 to pokemons.squirtle,
        8 to pokemons.wartortle,
        9 to pokemons.blastoise,
        10 to pokemons.caterpie,
        11 to pokemons.metapod,
        12 to pokemons.butterfree,
        13 to pokemons.weedle,
        14 to pokemons.kakuna,
        15 to pokemons.beedrill,
        16 to pokemons.pidgey,
        17 to pokemons.pidgeotto,
        18 to pokemons.pidgeot,
        19 to pokemons.rattata,
        20 to pokemons.raticate,
        21 to pokemons.spearow,
        22 to pokemons.fearow,
        23 to pokemons.ekans,
        24 to pokemons.arbok,
        25 to pokemons.pikachu,
        26 to pokemons.raichu,
        27 to pokemons.sandshrew,
        28 to pokemons.sandslash,
        29 to pokemons.nidoranF,
        30 to pokemons.nidorina,
        31 to pokemons.nidoqueen,
        32 to pokemons.nidoranM,
        33 to pokemons.nidorino,
        34 to pokemons.nidoking,
        35 to pokemons.clefairy,
        36 to pokemons.clefable,
        37 to pokemons.vulpix,
        38 to pokemons.ninetales,
        39 to pokemons.jigglypuff,
        40 to pokemons.wigglytuff,
        41 to pokemons.zubat,
        42 to pokemons.golbat,
        43 to pokemons.oddish,
        44 to pokemons.gloom,
        45 to pokemons.vileplume,
        46 to pokemons.paras,
        47 to pokemons.parasect,
        48 to pokemons.venonat,
        49 to pokemons.venomoth,
        50 to pokemons.diglett,
        51 to pokemons.dugtrio,
        52 to pokemons.meowth,
        53 to pokemons.persian,
        54 to pokemons.psyduck,
        55 to pokemons.golduck,
        56 to pokemons.mankey,
        57 to pokemons.primeape,
        58 to pokemons.growlithe,
        59 to pokemons.arcanine,
        60 to pokemons.poliwag,
        61 to pokemons.poliwhirl,
        62 to pokemons.poliwrath,
        63 to pokemons.abra,
        64 to pokemons.kadabra,
        65 to pokemons.alakazam,
        66 to pokemons.machop,
        67 to pokemons.machoke,
        68 to pokemons.machamp,
        69 to pokemons.bellsprout,
        70 to pokemons.weepinbell,
        71 to pokemons.victreebel,
        72 to pokemons.tentacool,
        73 to pokemons.tentacruel,
        74 to pokemons.geodude,
        75 to pokemons.graveler,
        76 to pokemons.golem,
        77 to pokemons.ponyta,
        78 to pokemons.rapidash,
        79 to pokemons.slowpoke,
        80 to pokemons.slowbro,
        81 to pokemons.magnemite,
        82 to pokemons.magneton,
        83 to pokemons.farfetchd,
        84 to pokemons.doduo,
        85 to pokemons.dodrio,
        86 to pokemons.seel,
        87 to pokemons.dewgong,
        88 to pokemons.grimer,
        89 to pokemons.muk,
        90 to pokemons.shellder,
        91 to pokemons.cloyster,
        92 to pokemons.gastly,
        93 to pokemons.haunter,
        94 to pokemons.gengar,
        95 to pokemons.onix,
        96 to pokemons.drowzee,
        97 to pokemons.hypno,
        98 to pokemons.krabby,
        99 to pokemons.kingler,
        100 to pokemons.voltorb,
        101 to pokemons.electrode,
        102 to pokemons.exeggcute,
        103 to pokemons.exeggutor,
        104 to pokemons.cubone,
        105 to pokemons.marowak,
        106 to pokemons.hitmonlee,
        107 to pokemons.hitmonchan,
        108 to pokemons.lickitung,
        109 to pokemons.koffing,
        110 to pokemons.weezing,
        111 to pokemons.rhyhorn,
        112 to pokemons.rhydon,
        113 to pokemons.chansey,
        114 to pokemons.tangela,
        115 to pokemons.kangaskhan,
        116 to pokemons.horsea,
        117 to pokemons.seadra,
        118 to pokemons.goldeen,
        119 to pokemons.seaking,
        120 to pokemons.staryu,
        121 to pokemons.starmie,
        122 to pokemons.mrMime,
        123 to pokemons.scyther,
        124 to pokemons.jynx,
        125 to pokemons.electabuzz,
        126 to pokemons.magmar,
        127 to pokemons.pinsir,
        128 to pokemons.tauros,
        129 to pokemons.magikarp,
        130 to pokemons.gyarados,
        131 to pokemons.lapras,
        132 to pokemons.ditto,
        133 to pokemons.eevee,
        134 to pokemons.vaporeon,
        135 to pokemons.jolteon,
        136 to pokemons.flareon,
        137 to pokemons.porygon,
        138 to pokemons.omanyte,
        139 to pokemons.omastar,
        140 to pokemons.kabuto,
        141 to pokemons.kabutops,
        142 to pokemons.aerodactyl,
        143 to pokemons.snorlax,
        144 to pokemons.articuno,
        145 to pokemons.zapdos,
        146 to pokemons.moltres,
        147 to pokemons.dratini,
        148 to pokemons.dragonair,
        149 to pokemons.dragonite,
        150 to pokemons.mewtwo,
        151 to pokemons.mew)

    return pokemonsDisponiveis
}